### ISSUE TITLE
Make dialog smaller. Usefull for TVs

### ISSUE THREAD

**Issue by trudyhood** [vpnhood/VpnHood.Client.WebUI#1]
![image](https://github.com/vpnhood/VpnHood.Client.WebUI2/assets/72891124/0ee8499c-ae03-4828-b219-700610e0ce2d)

**Comment by trudyhood** [comment]
same as other dialogs. make them have max width
![image](https://github.com/vpnhood/VpnHood.Client.WebUI2/assets/72891124/dd659820-6490-4c7d-968f-e2e3bd14b696)

**Comment by petervhood** [comment]
Done
