### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lightlus** [vpnhood/VpnHood.Client.WebUI#11]
Cannot read properties of null (reading 'find')

**Comment by lightlus** [comment]
compile runtime error

**Comment by trudyhood** [comment]
@petervhood We need to work on dev branch and keep the main sync with VpnHood

**Comment by petervhood** [comment]
I didn’t see any issues; however, new changes were applied and tested.

**Comment by trudyhood** [comment]
@lightlus We would be grateful if you could check the recent commit in the main branch and let us know if there is any issue.
